package lexer.token;

public enum TokenType {
    INT, BEGIN, END, FUNCTION, IF, OR, ELSE, FOR, GOES, FROM, TO, CALL,
    IDENT, INT_LIT,
    LPAREN, RPAREN, LBRACKET, RBRACKET, SEPARATOR_COMMA, TYPE_COLON,
    ADD, SUBTRACT, MULTIPLY, DIVIDE, PERCENT,
    LT, LE, GT, GE, EQ, NEQ,
    ASSIGN,
    NEWLINE, EOF,
    IZVOLITE,PORUDZBINA,RACUN,PREDJELO,USLUZENNEUSLUZEN,JELOVNIK,LISTACEKANJA,
    DACETEMI,KONOBAR,
    REZERVISANSTO,SLOBODANSTO,JESCEMONEGDEDRUGO,
    NOVATURA,DOKNEDOBIJEMOBROK,RADINESTO,
    NAPLATI,STO,NAPLACENO,
    RECEPT,RETURN,GLAVNIOBROK,
    TRUE,FALSE,
    JE,UKUPNO,MANJE,PUTA,DELJENO,KUSUR

}
