package lexer.token;

public enum TokenType {

     AND, OR,
     IDENT, INT_LIT,
    LPAREN, RPAREN, LBRACKET, RBRACKET, LBRACE, RBRACE, SEPARATOR_COMMA, TYPE_COLON,SEMICOLON,
    LT, LE, GT, GE, EQ, NEQ, NOT,EQUAL,
    NEWLINE, EOF,

    DOUBLE_LIT,STRING_LIT,CHAR_LIT,
    IZVOLITE,PORUDZBINA,RACUN,PREDJELO,USLUZENNEUSLUZEN,JELOVNIK,LISTACEKANJA,
    DACETEMI,KONOBAR,
    REZERVISANSTO,SLOBODANSTO,JESCEMONEGDEDRUGO,
    NOVATURA,DOKNEDOBIJEMOBROK,RADINESTO,
    NAPLATI,STO,NAPLACENO,
    RECEPT,RETURN,GLAVNIOBROK,
    TRUE,FALSE,USLUZEN,NEUSLUZEN,
    JE,UKUPNO,MANJE,PUTA,DELJENO,KUSUR

}
